---
title: "R Notebook"
author: "Fatemeh Nadi"
date: "Dec 2022"
output: html_document
---

# 8 - (R)
  


```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(ggmosaic)
library(tidyverse)
theme_set(theme_minimal(20))

```



<b> read data </b>

```{r}
# Read CSV into DataFrame
diet = read.csv('./Diet.csv')
head (diet)
```



Plot the three group’s data using side-by-side boxplots.
## <b> a. </b>
```{r}
#preprocessing
diet <- diet %>%
  mutate(Diet = recode_factor(Diet, `1` = "A", `2` = "B", `3` = "C")) %>%
  mutate_at(c("gender"),
            ~ recode_factor(.x, `0` = "Female", `1` = "Male"))


diet$weight.loss <- diet$pre.weight - diet$weight6weeks
diet$Diet  <- factor(diet$Diet,levels=c("A","B","C"))
diet$gender      <- factor(diet$gender,levels=c("Male","Female"))



#draw bpx plot
boxplot(diet$weight.loss  ~ diet$Diet, ylab = "Weight loss (kg)", xlab = "Diet type",
        main = "side-by-side boxplots") 
```

Use ANOVA in R to determine whether there is a significant difference in the mean
weight loss between groups
## <b> b. </b>
```{r}
fisher  = aov(weight.loss~Diet,data=diet)
```

Display and analyze the results.
## <b> c. </b>
```{r}
summary(fisher)
```

Compare the weight loss between the two groups in R and:
## <b> d. </b>
```{r}
gp <- unique(diet$Diet)

A <- diet$weight.loss[which(diet$Diet==gp[1])]
B <- diet$weight.loss[which(diet$Diet==gp[2])]

diet.t.test <- t.test(A , B)
diet.t.test
```

```{r}
# confidence interval for difference
diet.t.test$conf.int
```

